locale: "en-US"
title: Zach Feldman
title_separator: "-"
subtitle:
name: Zach Feldman
description: Zach Feldman â€“ Projects and CV
baseurl: "/fall-2025-portfolio-zachfeldman3"

theme: jekyll-theme-minimal
color_scheme: light

sass:
  style: compressed

collections:
  pages:
    output: true
    directory: _pages
  projects:
    output: true
    directory: _projects

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

